added a link to Treehouse online interactive tutorial for learning co…
Ladies-Storm-Hackathons/Resources pull request #49
Opened 2016-10-08 01:46 UTC by cheapwebmonkey

added a link to Treehouse online interactive tutorial for learning code  and a link and description to my fave Haskell learning resource

2016-10-08 04:04 UTC, aliceyoung9 commented on learning_resources.md
Please add a note that Treehouse is not free.

2016-10-08 04:16 UTC, aceyoung9 requested changes
We've stuck to only listing free/gratis resources so far, but I'd be willing to add these resources if you list the costs in the description. Thanks!

2016-10-08 04:16 UTC, aliceyoung9 commented on learning_resources.md
> +* [Haskell Programming from First Principles](http://haskellbook.com)
Please add that the first chapter is offered as a free sample, and list the price of the book.

2016-10-08 16:36 UTC, cheapwebmonkey commented
Added the monthly pricing for Treehouse and the info that is is free if your public library participates in their program- you can check out a license. Added the info about the Haskell book being free for the first chapter, then $59

2016-10-08 17:08 UTC, aceyoung9 approved these changes

2016-10-08 17:08 UTC, aliceyoung9 commented
Out of curiosity, which public library has Treehouse licenses to check out? That's excellent!

2016-10-08 17:09 UTC, merged

2016-10-08 21:37 UTC, cheapwebmonkey commented on learning_resources.md
> +* [Haskell Programming from First Principles](http://haskellbook.com)
Added

2016-10-08 21:39 UTC, cheapwebmonkey commented
The Louisville Free Public Library offers this. It is in Louisville, KY.  I am certain other places around the country do as well. I think usually libraries that offer Lynda.com checkouts, offer Treehouse. People should check with their local branches.

2016-10-09 06:38 UTC, aliceyoung9 commented
Wow! Thanks for sharing!